### ISSUE TITLE
I'm having an issue where the action still merges a major release even if the target is set to minor.

### ISSUE THREAD

**Issue by simoneb** [fastify/github-action-merge-dependabot#166]
I'm having an issue where the action still merges a major release even if the target is set to minor.

For example, React v17.0.2 to v18.0.0 still gets merged.

```
    automerge:
        needs: analyze
        runs-on: ubuntu-latest
        permissions:
            pull-requests: write
            contents: write
        if: ${{ github.event_name == 'pull_request' }}
        steps:
            -   uses: fastify/github-action-merge-dependabot@v3
                with:
                    github-token: ${{ secrets.GITHUB_TOKEN }}
                    target: minor
```

Example PR: https://github.com/austins/smoothnanners-web/pull/17

_Originally posted by @austins in https://github.com/fastify/github-action-merge-dependabot/issues/124#issuecomment-1085084222_
