### ISSUE TITLE
Error while parsing PR title.

### ISSUE THREAD

**Issue by annihilatorrrr** [fastify/github-action-merge-dependabot#274]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.3.1

### Node.js version

14.x

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

ubuntu-latest

### Description

A error occurs in the action:
```
Error while parsing PR title, expected: `bump <package> from <old-version> to <new-version>`
```

### Steps to Reproduce

This was the pr title which it failed to merge with a error rest prs it can merge successfully:

```
Update regex requirement from ~=2022.9.11 to ~=2022.9.13 (#226)
```

Here's my action.yml:

```
name: Auto Merge
on:
  pull_request:

jobs:
  merger:
    name: Merger
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - name: Merge
      uses: fastify/github-action-merge-dependabot@v3.3.1
```

### Expected Behavior

The pr should get merged.
