### ISSUE TITLE
Fails to update workflow 

### ISSUE THREAD

**Issue by SteveBox0** [fastify/github-action-merge-dependabot#333]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3.5.3

### Plugin version

NA

### Node.js version

NA

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

runs-on: ubuntu-latest

### Description

Fails to merge "Bump actions/checkout from 3.1.0 to 3.2.0" using 

```
on:
  - pull_request_target

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
```

The pull request stays open and never gets merged. 
![image](https://user-images.githubusercontent.com/86661487/207279491-318c963f-b06d-48bb-937c-6012433565e7.png)
![image](https://user-images.githubusercontent.com/86661487/207279783-d3566874-de57-4c79-8a4d-9d20f94400a1.png)

### Steps to Reproduce

Create any simple workflow that has actions/checkout 3.1.0 and dependabot.yml with the below config.

```
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
```

### Expected Behavior

Pull request to be merged

**Comment by simoneb** [comment]
You can't use the pull_request_target event. See how to use it in the docs.

**Comment by SteveBox0** [comment]
When testing with pull_request using an example matching your docs i get the below error.

Error: refusing to allow a GitHub App to create or update workflow `.github/workflows/update-repo.yml` without `workflows` permission that can be set 

"workflows" does not seem to be a for GITHUB_TOKEN.

```
name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            path: 'Repo'     
            
      - name: Run check
        run: |
            ls
  automerge:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
```
