### ISSUE TITLE
Add GHES support

### ISSUE THREAD

**Issue by frequ** [fastify/github-action-merge-dependabot#363]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

Currently automerging dependabot PRs does not work in GitHub Enterprise Server environment.
You'll get error from `dependabot/fetch-metadata@v1`.
```
Warning: Dependabot's commit signature is not verified, refusing to proceed.
Error: PR is not from Dependabot, nothing to do.
```

I believe this could be easily solved just by passing `skip-commit-verification` to `dependabot/fetch-metadata@v1` (https://github.com/dependabot/fetch-metadata) action.

I'd propose adding new input `skip-commit-verification` and then passing it to `dependabot/fetch-metadata@v1`.

### Motivation

Support for GHES.

### Example

```yml
steps:
  - name: Automerge GHES dependabot PR
    uses: fastify/github-action-merge-dependabot@v3
    with:
      skip-commit-verification: true
```
