### ISSUE TITLE
I can't get `use-github-auto-merge: true` to work

### ISSUE THREAD

**Issue by max-sixty** [fastify/github-action-merge-dependabot#431]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

3

### Node.js version

16

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

ubuntu-latest

### Description

I've tried lots of permutations but can't get the `auto-merge` to simulate clicking "Auto-Merge".

### Steps to Reproduce

Here's an example commit: https://github.com/PRQL/prql/pull/2670/commits/d05316bfa3d79c9a5b2aac5321d17b40e5057eb5

Relevant YAML:

```yaml
    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-github-auto-merge: true
```

Here's the action from that commit: https://github.com/PRQL/prql/actions/runs/5138796584/jobs/9248663951

There's no logging from the action — though it passes — so I'm not sure how to debug further
