### ISSUE TITLE
Different targets for `development` and `production` dependencies

### ISSUE THREAD

**Issue by nicolasrouanne** [fastify/github-action-merge-dependabot#443]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be nice if we could configure different rules for `development` and `production` dependencies. Something such as
```yml
- uses: fastify/github-action-merge-dependabot@v3
   with:
     target:
       production: patch
       development: any
```

### Motivation

I tend to separate `devDependencies` (e.g. `prettier`, `eslint`, etc.) from `dependencies`. Same applies in `ruby` for instance.
I like to merge everything that doesn't impact production as soon as it becomes available; however I'm more careful regarding packages that can impact our production app... I don't have enough coverage to be 100% sure.

### Example

Here is the syntax from [`ahmadnassri/action-dependabot-auto-merge`](https://github.com/ahmadnassri/action-dependabot-auto-merge/tree/45fc124d949b19b6b8bf6645b6c9d55f4f9ac61a#configuration-file-syntax) which is nice IMO
```yml
- match:
    dependency_name: aws-sdk
    update_type: semver:minor

- match:
    dependency_type: development
    update_type: semver:minor # includes patch updates!

- match:
    dependency_type: production
    update_type: security:minor # includes patch updates!

- match:
    dependency_type: production
    update_type: semver:patch
```
