### ISSUE TITLE
"Fetch metadata" step is skipped for "pull_request_target"

### ISSUE THREAD

**Issue by kirillsud** [fastify/github-action-merge-dependabot#475]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Fastify version

-

### Node.js version

-

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

The step `Fetch metadata` is skipped for a workflow triggered by the `pull_request_target`. The issue was found the first time approximately on the 28th of August. Before the date, there was no issue with the same workflow file. It seems something has been changed in GitHub Workflow implementation, but I couldn't find any evidence.

`dependabot-auto-merge.yml` content:

```
name: Dependabot
on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  Auto-merge:
    runs-on: ubuntu-latest

    steps:
      - uses: fastify/github-action-merge-dependabot@v3
        with:
          use-github-auto-merge: true
          target: minor
```

### Steps to Reproduce

1. Create a repo with a NodeJS project and some not the latest dependencies in `package.json`
2. Setup dependabot to create PRs with updates
3. Enable auto-merge feature
4. Create a workflow with the content from the description
5. Commit the workflow to the `main`/`master` branch
6. Wait for a PR from dependabot
7. Check the **Dependabot / Auto-merge** check result for the PR

### Expected Behavior

The step `dependabot/fetch-metadata` has been executed for the action `github-action-merge-dependabot`.
