### ISSUE TITLE
Feature: Allow defining targets per pattern or group

### ISSUE THREAD

**Issue by jmullo** [fastify/github-action-merge-dependabot#513]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the feature has not already been requested

### 🚀 Feature Proposal

It would be very useful to be able to define target levels per pattern or group.

Not matching ones would use default target.

### Motivation

For certain dependencies we know that it's safe to automerge majors and for some other dependencies it's not.

### Example

```
target: minor
custom-targets:
  - target: major
    patterns:
      - "@foo*"
    groups:
      - "dev-dependencies"
```
