### ISSUE TITLE
Documentation inconsistent with GitHub Actions schema

### ISSUE THREAD

**Issue by kibertoad** [fastify/github-action-merge-dependabot#53]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

3.x.x

### Plugin version

2.2.0

### Node.js version

14.x

### Operating system

Windows

### Operating system version (i.e. 20.04, 11.3, 10)

-

### Description

Documentation for this action suggests doing following for excluding certain packages:

```
steps:
  - uses: fastify/github-action-merge-dependabot@v2.1.1
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      exclude: ['react']
```

However, according to https://json.schemastore.org/github-workflow.json, entries for  `with` (which have type of `env`), should be this:

```
        "oneOf": [
          {
            "type": "string"
          },
          {
            "type": "number"
          },
          {
            "type": "boolean"
          }
        ]
```

Hence passing an array here does not pass the schema validation.

### Steps to Reproduce

Pass an `exclude` parameter as suggested by documentation.
I believe this can also be observed here: https://github.com/pinojs/pino/commit/4a55e541c5126f5c07f41941288bbe53364c3da9

### Expected Behavior

Implementation is consistent with GA schema.
