### ISSUE TITLE
Failed with status code 400

### ISSUE THREAD

**Issue by moroine** [fastify/github-action-merge-dependabot#67]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure it has not already been reported

### Fastify version

2.4.0

### Node.js version

n/a

### Operating system

Linux

### Operating system version (i.e. 20.04, 11.3, 10)

20.04.2

### Description

I'm using the following configuration:

```yaml
name: auto-merge

on:
  pull_request_target:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.4.0
        with:
          target: minor
          merge-method: merge
          github-token: ${{ secrets.GH_TOKEN }}
```

I have installed the application on the repository `nugit/transformer-service` where the action is enabled. But it's failing with the following error:

```
Error: Request failed with status code 400: {"statusCode":400,"error":"Bad Request","message":"See https://github.com/fastify/github-action-merge-dependabot#usage - {\"message\":\"You must authenticate with an installation access token in order to list repositories for an installation.\",\"documentation_url\":\"https://docs.github.com/rest/reference/apps#list-repositories-accessible-to-the-app-installation\"}"}
```

### Steps to Reproduce

See description

**Comment by simoneb** [comment]
Did you install the GitHub application on the repo as described in the readme?

**Comment by moroine** [comment]
Yes, see the following authorizations 
![image](https://user-images.githubusercontent.com/4658821/130455616-8e9f0af7-1d60-4eac-8d9c-f50481927575.png)

**Comment by simoneb** [comment]
Ok cool, so I guess the problem may lie in the fact that you're using `pull_request_target` as a trigger. Can you try to change it to `pull_request` to see if that fixes it. Using `pull_request_target` is something I have not tried so I'm not sure what to expect when you use it.

**Comment by moroine** [comment]
> Ok cool, so I guess the problem may lie in the fact that you're using `pull_request_target` as a trigger. Can you try to change it to `pull_request` to see if that fixes it. Using `pull_request_target` is something I have not tried so I'm not sure what to expect when you use it.

Will try it, but the issue I have is to run unit tests you need to use `pull_request_target` in order to have secrets available to the action. So I think I'd need to use `workflow_run` event to merge only when tests passes?

**Comment by simoneb** [comment]
Fair point. So your workflow needs to run on `pull_request_target` because without that you don't have access to secrets that you need in your tests, right? If so, it makes sense. We will need to figure out what we need to change in the action to also support `pull_request_target`, assuming that it's possible to do so.

**Comment by moroine** [comment]
I also try with `workflow_run` and it's not working too. 

Here is my action:
```yaml
name: auto-merge

on:
  workflow_run:
    workflows: ["dependabot-check"]
    types: 
      - completed

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.4.0
        with:
          target: minor
          merge-method: merge
          github-token: ${{ secrets.GH_TOKEN }}
          pr-number: ${{ github.event.workflow_run.pull_requests[0].number }}
```

And here is the output 
![image](https://user-images.githubusercontent.com/4658821/131407379-c58f577a-fea3-4787-8207-f3c48b7ae550.png)


Maybe it's because `GH_TOKEN` is an organization secret and not a repository secret 🤔 


@gilach I tried with `secrets.GITHUB_TOKEN` and **it's working** 🎉  thank you so much.
